#ifndef PROJECT228_CONSTANTS_H
#define PROJECT228_CONSTANTS_H

const int MAP_WIDTH_FIRST = 64;
const int MAP_HEIGHT_FIRST = 47;
const int TILES_CNT = 45;
const int TILE_SIZE = 64;

#endif  // PROJECT228_CONSTANTS_H
